apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: microservices-demo-cluster
  region: us-east-1
  version: "1.34"

vpc:
  cidr: 10.0.0.0/16

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 40
    #ssh:
    #  allow: true
    #  publicKeyName: my-ec2-key
    iam:
      withAddonPolicies:
        ebs: true
        cloudWatch: true

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: latest
    resolveConflicts: overwrite
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
